source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def need_pods
    pod 'Moya', '~> 12.0'
    pod 'SwiftyJSON', '~> 4.0'
end

target 'ProjectTemplate' do
#    need_pods
end

target 'ProjectTemplate Dev' do
#    need_pods
end

target 'NetworkService' do
    need_pods
end

target 'Business' do
    pod 'SnapKit'
    pod 'Material'
end

post_install do |installer|       
   installer.pods_project.targets.each do |target| 
     puts target.name 
   end
end
